### ISSUE TITLE
Sentence splitter changes some letters in the text

### ISSUE THREAD

**Issue by piyarathnalakmali** [ysenarath/sinling#3]
Input text = "**ශ්‍රී** ලංකන් ගුවන් සේවය පිළිබඳව **අධ්‍යයනය** කර වාර්තාවක් සැපයීම සඳහා වරාය හා ගුවන් සේවා **අමාත්‍යවරයා** විසින් පත් කළ ජේ.සී. වැලිඅමුණ කමිටුව සිය වාර්තාව **අග්‍රාමාත්‍ය** රනිල් **වික්‍රමසිංහ** වෙත ඊයේ භාරදුන්නා. ඒ අරලියගහ මන්දිරයේ පැවති උත්සවයකදියි."

Output text = "**ශ්රී** ලංකන් ගුවන් සේවය පිළිබඳව **අධ්යයනය** කර වාර්තාවක් සැපයීම සඳහා වරාය හා ගුවන් සේවා **අමාත්යවරයා** විසින් පත් කළ ජේ.සී. වැලිඅමුණ කමිටුව සිය වාර්තාව **අග්රාමාත්ය** රනිල් **වික්රමසිංහ** වෙත ඊයේ භාරදුන්නා
ඒ අරලියගහ මන්දිරයේ පැවති උත්සවයකදියි"

The highlighted words in the input are changed in the output text.

**Comment by ysenarath** [comment]
@piyarathnalakmali Please check whether the error is resolved now. I removed the part that removes the special character that enables seeing words like `ශ්‍රී` correctly. 

Thanks.

PS: You might not be able to see it in the terminal if it is not able to show these special characters.

**Comment by piyarathnalakmali** [comment]
@ysenarath It is fixed. Thank you
